<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * @copyright       The XUUPS Project http://sourceforge.net/projects/xuups/
 * @license         http://www.fsf.org/copyleft/gpl.html GNU public license
 * @package         Shoutbox
 * @author          Alphalogic <alphafake@hotmail.com>
 * @author          tank <tanksplace@comcast.net>
 * @author          trabis <lusopoemas@gmail.com>
 * @version         $Id: xoops_version.php 0 2010-01-29 18:47:04Z trabis $
 */

if (!defined('XOOPS_ROOT_PATH')) {
	die('XOOPS root path not defined');
}

$modversion['name']        = _MI_SHOUTBOX_NAME;
$modversion['version']     = '5.01';
$modversion['description'] = _MI_SHOUTBOX_DESC;
$modversion['credits']     = "The XOOPS Project";
$modversion['help']        = 'page=help';
$modversion['license']     = 'GNU GPL 2.0 or later';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html";
$modversion['official']    = 0;
$modversion['image']       = "images/module_logo.png";
$modversion['dirname'] = basename(dirname(__FILE__));
$modversion['author']      = 'Tank, Trabis';

$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16']        = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32']        = '../../Frameworks/moduleclasses/icons/32';
//about
$modversion['release_date']        = '2013/08/10';
$modversion["module_website_url"] = "www.xoops.org";
$modversion["module_website_name"] = "XOOPS";
$modversion["module_status"]       = "Final";
$modversion['min_php']             = '5.2';
$modversion['min_xoops']           = "2.5.6";
$modversion['min_admin']           = '1.1';
$modversion['min_db']              = array(
    'mysql'  => '5.0.7', 'mysqli' => '5.0.7'
);

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "shoutbox";

// Blocks
$modversion['blocks'][1]['file'] = "shoutbox.php";
$modversion['blocks'][1]['name'] = _MI_SHOUTBOX_BLOCK;
$modversion['blocks'][1]['description'] = _MI_SHOUTBOX_DESC;
$modversion['blocks'][1]['show_func'] = "b_shoutbox_show";
$modversion['blocks'][1]['template'] = 'shoutbox_block.html';

// Menu
$modversion['hasMain'] = 0;

// Templates
$modversion['templates'][1]['file'] = 'shoutbox_popup.html';
$modversion['templates'][1]['description'] = 'Template for popup';
$modversion['templates'][2]['file'] = 'shoutbox_shoutframe.html';
$modversion['templates'][2]['description'] = 'Template for block-iframe content';
$modversion['templates'][3]['file'] = 'shoutbox_popupframe.html';
$modversion['templates'][3]['description'] = 'Template for popup-iframe content';
$modversion['templates'][4]['file'] = 'shoutbox_popupheader.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'shoutbox_online.html';
$modversion['templates'][5]['description'] = '';

$modversion['onInstall'] = 'include/module.php';
$modversion['onUninstall'] = 'include/module.php';

// Config settings
// Global settings:
$i=0;
$modversion['config'][$i]['name'] = 'logfile';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_CAT1';
$modversion['config'][$i]['description'] = '_MI_USERLOG_CONFCAT_LOGFILE_DSC';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'odd';
$i++;
$modversion['config'][$i]['name'] = 'guests_may_post';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE1';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_EMPTY';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'guests_may_chname';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE2';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC2';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'allow_bbcode';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE3';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC3';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'stamp_format';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE4';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC4';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'h:i a';
$i++;
$modversion['config'][$i]['name'] = 'maxshouts_trim';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE5';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC5';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '20';
$i++;
$modversion['config'][$i]['name'] = 'maxshouts_view';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE6';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC6';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '20';
$i++;
$modversion['config'][$i]['name'] = 'storage_type';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE7';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC7';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array('_MI_SHOUTBOX_OP7_F' => 'file', '_MI_SHOUTBOX_OP7_D' => 'database');
$modversion['config'][$i]['default'] = 'file';
$i++;
$modversion['config'][$i]['name'] = 'user_realname';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE8';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC8';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;

// Block Settings:
$i++;
$modversion['config'][$i]['name'] = 'logfile';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_CAT2';
$modversion['config'][$i]['description'] = '_MI_USERLOG_CONFCAT_LOGFILE_DSC';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'odd';
$i++;
$modversion['config'][$i]['name'] = 'show_smileybar';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE11';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_EMPTY';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'iframe_width';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE12';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC12';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '100%';
$i++;
$modversion['config'][$i]['name'] = 'iframe_height';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE13';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC13';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '150';
$i++;
$modversion['config'][$i]['name'] = 'iframe_border';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE14';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_EMPTY';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '0';
$i++;
$modversion['config'][$i]['name'] = 'popup';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE15';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC15';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'block_autorefresh';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE16';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC16';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['options'] = Array('_MI_SHOUTBOX_OP16_BA0' => 0, '_MI_SHOUTBOX_OP16_BA1' => 1);
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'wordwrap_setting';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE17';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC17';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'display_avatar';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE18';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC18';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'guest_avatar';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE19';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC19';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['options'] = array('_MI_SHOUTBOX_OP19_GA0' => 0, '_MI_SHOUTBOX_OP19_GA1' => 1, '_MI_SHOUTBOX_OP19_GA2' => 2, '_MI_SHOUTBOX_OP19_GA3' => 3, '_MI_SHOUTBOX_OP19_GA4' => 4, '_MI_SHOUTBOX_OP19_GA5' => 5);
$modversion['config'][$i]['default'] = 1;

// PopUp:
$i++;
$modversion['config'][$i]['name'] = 'logfile';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_CAT3';
$modversion['config'][$i]['description'] = '_MI_USERLOG_CONFCAT_LOGFILE_DSC';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'odd';
$i++;
$modversion['config'][$i]['name'] = 'popup_whoisonline';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE31';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC31';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'popup_show_smileybar';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE32';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_EMPTY';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'popup_sound';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE33';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_EMPTY';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'popup_guests';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE34';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC34';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'popup_irc';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE35';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC35';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'popup_autofocus';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE36';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC36';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'popup_width';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE37';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC37';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '500';
$i++;
$modversion['config'][$i]['name'] = 'popup_height';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE38';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC38';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '340';

// Text Input:
$i++;
$modversion['config'][$i]['name'] = 'logfile';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_CAT4';
$modversion['config'][$i]['description'] = '_MI_USERLOG_CONFCAT_LOGFILE_DSC';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'odd';
$i++;
$modversion['config'][$i]['name'] = 'input_type';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE40';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC40';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['options'] = Array('_MI_SHOUTBOX_OP40_TL' => 0, '_MI_SHOUTBOX_OP40_TA' => 1);
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'textarea_rows';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE41';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC41';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '4';
$i++;
$modversion['config'][$i]['name'] = 'textarea_cols';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE42';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC42';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '75';
$i++;
$modversion['config'][$i]['name'] = 'text_linelength';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE43';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC43';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '75';
$i++;
$modversion['config'][$i]['name'] = 'text_maxchars';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE44';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC44';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '300';
$i++;
$modversion['config'][$i]['name'] = 'input_alerts';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE45';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC45';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'captcha_enable';
$modversion['config'][$i]['title'] = '_MI_SHOUTBOX_TITLE46';
$modversion['config'][$i]['description'] = '_MI_SHOUTBOX_DESC46';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;